### ISSUE TITLE
CMD window appears in Windows 

### ISSUE THREAD

**Issue by bryan-pardo** [TEAMuP-dev/HARP#170]
When the gradio client reaches out to the web, a CMD window appears on the screen and stays on the screen until the gradio client either gets an answer or times out. This is ugly. Can we hide this window?

This behavior is in Harp 1.1 and 1.2.X

**Comment by NathanPruyne** [comment]
6044c68 should ensure no window pops up for a call to `gradiojuce_client.exe`, but the root cause of this is that a call to `std::system` will always generate this window (regardless of program called). It seems like the way around this would be to change that call, which is already mentioned in the code and is now in #172.

**Comment by bryan-pardo** [comment]
This was fixed!
